const { PERMISSIONS } = require('./permissions');

const ROLES = {
  citizen: 'citizen',
  police: 'police',
  fire: 'fire',
  medical: 'medical',
  admin: 'admin',
};

const ROLE_PERMISSIONS = {
  [ROLES.citizen]: [
    PERMISSIONS.CITIZEN_INCIDENT_CREATE,
    PERMISSIONS.CITIZEN_INCIDENT_READ_OWN,
    PERMISSIONS.CITIZEN_ANALYTICS_READ_OWN,
  ],

  [ROLES.police]: [
    PERMISSIONS.POLICE_INCIDENT_READ_ASSIGNED,
    PERMISSIONS.POLICE_INCIDENT_UPDATE_ASSIGNED,
    PERMISSIONS.POLICE_ANALYTICS_READ,
  ],

  [ROLES.fire]: [
    PERMISSIONS.FIRE_INCIDENT_READ_ASSIGNED,
    PERMISSIONS.FIRE_INCIDENT_UPDATE_ASSIGNED,
    PERMISSIONS.FIRE_ANALYTICS_READ,
  ],

  [ROLES.medical]: [
    PERMISSIONS.MEDICAL_INCIDENT_READ_ASSIGNED,
    PERMISSIONS.MEDICAL_INCIDENT_UPDATE_ASSIGNED,
    PERMISSIONS.MEDICAL_ANALYTICS_READ,
  ],

  [ROLES.admin]: [
    // keep admin small and explicit
    PERMISSIONS.ADMIN_USERS_READ,
    PERMISSIONS.ADMIN_USERS_DELETE,
  ],
};

module.exports = { ROLES, ROLE_PERMISSIONS };

